services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: poc-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: poc-rabbitmq
    ports:
      - "5672:5672"   # Broker
      - "15672:15672" # Painel de controle

  grafana:
    image: grafana/grafana:latest
    container_name: poc-grafana
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch

  loja-service:
    build:
      context: .
      dockerfile: loja-service/Dockerfile
    container_name: poc-loja-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq

  collector-service:
    build:
      context: .
      dockerfile: collector-service/Dockerfile
    container_name: poc-collector-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      - rabbitmq
      - elasticsearch