spring.application.name=loja-service
server.port=8080
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

spring.datasource.url=jdbc:postgresql://localhost:5432/storedb
spring.datasource.username=storeuser
spring.datasource.password=storepass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect