spring.application.name=collector-service
server.port=8081
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.index=metrics-poc

collector.batch.size=100
collector.batch.flush-interval-ms=5000
